apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pod-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-pod-info
  template:
    metadata:
      labels:
        app: k8s-pod-info
    spec:
      containers:
      - name: fastapi
        image: f3lin/k8s-pod-info:v0.1.1
        ports:
        - containerPort: 8000
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-pod-info-service
spec:
  selector:
    app: k8s-pod-info
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000